[package]
name = "velocitystore"
version = "0.1.0"
description = "Aetheris OS Software Store"
authors = ["Aetheris OS App Store Team <store@aetheris-os.org>"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"
sqlite = "0.32"
quick-xml = "0.42"
landlock = "0.3"


