// File: style-dictionary/build.js
// Style Dictionary v4 build script to compile design tokens for Aetheris OS UI systems.

const fs = require('fs');
const path = require('path');

console.log("=== Aetheris OS Style Token Compiler (Style Dictionary v4) ===");

// Target Directories
const TARGETS = {
  gtk4: path.join(__dirname, '../config/gtk-4.0/gtk.css'),
  qt6: path.join(__dirname, '../config/qt6ct/qss/aetheris.qss'),
  labwc: path.join(__dirname, '../config/labwc/themerc'),
  css: path.join(__dirname, '../config/theme.css')
};

try {
  const StyleDictionary = require('style-dictionary');

  // 1. Register Custom Formatter for GTK4 CSS
  StyleDictionary.registerFormat({
    name: 'gtk4/css',
    formatter: function({ dictionary }) {
      let output = `/* Generated by Style Dictionary - GTK4 Custom Properties */\n`;
      dictionary.allTokens.forEach(token => {
        const varName = token.name.replace(/-/g, '_');
        output += `@define-color ${varName} ${token.value};\n`;
      });
      return output;
    }
  });

  // 2. Register Custom Formatter for Qt6 QSS
  StyleDictionary.registerFormat({
    name: 'qt6/qss',
    formatter: function({ dictionary }) {
      const bgToken = dictionary.allTokens.find(t => t.name.includes('dark-bg-100')) || { value: '#080A0F' };
      const textToken = dictionary.allTokens.find(t => t.name.includes('grey-100')) || { value: '#F4F6F9' };
      const borderToken = dictionary.allTokens.find(t => t.name.includes('dark-bg-200')) || { value: '#1E293B' };

      return `/* Generated by Style Dictionary - Qt6 QSS Stylesheet */
.QWidget {
  background-color: ${bgToken.value};
  color: ${textToken.value};
  border: 1px solid ${borderToken.value};
}
`;
    }
  });

  // 3. Register Custom Formatter for Labwc window-manager themerc
  StyleDictionary.registerFormat({
    name: 'labwc/themerc',
    formatter: function({ dictionary }) {
      const accentToken = dictionary.allTokens.find(t => t.name.includes('violet-600')) || { value: '#6366F1' };
      const bgToken = dictionary.allTokens.find(t => t.name.includes('dark-bg-000')) || { value: '#080A0F' };
      const borderToken = dictionary.allTokens.find(t => t.name.includes('dark-bg-200')) || { value: '#1E293B' };
      const textToken = dictionary.allTokens.find(t => t.name.includes('grey-100')) || { value: '#F4F6F9' };

      return `# Generated by Style Dictionary - Labwc themerc
window.active.border.color: ${accentToken.value}
window.active.title.bg.color: ${bgToken.value}
window.inactive.border.color: ${borderToken.value}
window.active.title.text.color: ${textToken.value}
border.width: 1
padding.width: 4
`;
    }
  });

  // 4. Register Custom Formatter for plain CSS Variables
  StyleDictionary.registerFormat({
    name: 'css/variables',
    formatter: function({ dictionary }) {
      let output = `/* Generated by Style Dictionary - CSS Custom Variables */\n:root {\n`;
      dictionary.allTokens.forEach(token => {
        output += `  --${token.name}: ${token.value};\n`;
      });
      output += `}\n`;
      return output;
    }
  });

  const sd = new StyleDictionary('style-dictionary/config.json');
  sd.buildAllPlatforms();
  console.log("=== Compilation Successful ===");
} catch (e) {
  // Safe fallback if Style Dictionary library is missing/errors during early setup
  console.log("Style Dictionary compiler warning: " + e.message);
  console.log("Creating fallback configuration files directly...");

  const baseTokenPath = path.join(__dirname, 'tokens/base.json');
  if (fs.existsSync(baseTokenPath)) {
    const tokens = JSON.parse(fs.readFileSync(baseTokenPath, 'utf8'));
    const ultraviolet = tokens.color.accent['violet-600'].value;
    const darkObsidian = tokens.color.background['dark-bg-000'].value;
    const lightSlate = tokens.color.background['light-bg-000'].value;

    fs.mkdirSync(path.join(__dirname, '../config/gtk-4.0'), { recursive: true });
    fs.writeFileSync(path.join(__dirname, '../config/gtk-4.0/gtk.css'), `@define-color accent_color ${ultraviolet};\n@define-color window_bg_color ${darkObsidian};\n`);

    fs.mkdirSync(path.join(__dirname, '../config/qt6ct/qss'), { recursive: true });
    fs.writeFileSync(path.join(__dirname, '../config/qt6ct/qss/aetheris.qss'), `.QWidget { background-color: ${darkObsidian}; color: ${lightSlate}; }\n`);

    fs.mkdirSync(path.join(__dirname, '../config/labwc'), { recursive: true });
    fs.writeFileSync(path.join(__dirname, '../config/labwc/themerc'), `window.active.border.color: ${ultraviolet}\nwindow.active.title.bg.color: ${darkObsidian}\n`);

    fs.writeFileSync(path.join(__dirname, '../config/theme.css'), `:root { --accent-color: ${ultraviolet}; --bg-color: ${darkObsidian}; }\n`);
    console.log("Fallback files deployed successfully.");
  } else {
    console.error("Error: base.json tokens file missing! Cannot create theme files.");
  }
}
